#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# Auther: ArianOmrani - https://github.com/arian24b/
# git repository: https://github.com/arian24b/server_management_public

set -e
# set -x

clear

GIT_REPO=https://github.com/arian24b/server_management_public
RESOLVCONF=/etc/resolv.conf
RESOLVCONF_SYSTEMD=/run/systemd/resolve/resolv.conf
SYSCTLCONF=/etc/sysctl.d/99-sysctl.conf
TUNEDPROFILE=network-latency
TMPFILEDELETE=/home/.tempfilefordelete
RCLOCAL=/etc/rc.local
BACKUPPATH=/home/arian/backup


# Load Template
source <(curl -SskL $GIT_REPO/raw/main/template.sh)

# Change /etc/resolv.conf
curl -sSkL $GIT_REPO/raw/main/conf/resolv.conf -o $RESOLVCONF_SYSTEMD \
&& unlink $RESOLVCONF \
&& ln -s $RESOLVCONF_SYSTEMD $RESOLVCONF
Green_msg "$RESOLVCONF changed!"

# Update and install packages
add-apt-repository ppa:deadsnakes/ppa --yes >/dev/null 2>&1

apt-get update --fix-missing --quiet --quiet --yes
apt-get upgrade --fix-broken --fix-missing --quiet --quiet --yes
apt-get dist-upgrade --fix-broken --fix-missing --quiet --quiet --yes
Green_msg "System updated!"

apt-get remove --fix-broken --fix-missing --quiet --quiet --yes --autoremove snapd

apt-get --fix-broken --fix-missing --quiet --quiet --yes install nload iotop htop atop axel curl \
wget build-essential sudo git tmux screen nano ca-certificates gnupg lsb-release tree socat \
moreutils dnsutils unzip perl iptables libio-socket-ssl-perl libcrypt-ssleay-perl \
libnet-libidn-perl libio-socket-inet6-perl libsocket6-perl brotli net-tools tuned \
software-properties-common socat cron vim wget sendmail ipython3 python3 python3-pip \
zstd zip python3-venv python3.12 python3.12-venv dphys-swapfile libc++-dev software-properties-common netcat
Green_msg "Packages are installed!"

apt-get --fix-broken --fix-missing --quiet --quiet --yes autoremove
apt-get --fix-missing --quiet --quiet --yes clean
apt-get --fix-missing --quiet --quiet --yes autoclean

dpkg --configure -a
Green_msg "apt cleaned"

# Update ca-certificates
update-ca-certificates
Green_msg "ca-certificates Updated!"

# Config tuned
systemctl restart tuned
tuned-adm profile $TUNEDPROFILE
tuned-adm verify || true
Green_msg "tuned profile set to $TUNEDPROFILE"

# Update /etc/sysctl.conf
curl -sSkL $GIT_REPO/raw/main/conf/sysctl.conf -o $SYSCTLCONF \
&& sysctl --ignore -p --quiet --quiet
Green_msg "$SYSCTLCONF changed!"

# Install pip for python3.12
curl -sSkL https://github.com/pypa/get-pip/raw/main/public/get-pip.py | python3.12

# Config swap
curl -sSkL $GIT_REPO/raw/main/conf/dphys-swapfile -o /etc/dphys-swapfile \
&& dphys-swapfile setup \
&& dphys-swapfile swapon
rm -f /swapfile \
&& sed -i '/\/swapfile/d' /etc/fstab
Green_msg "swap created!"

# Add ssh-key to root user
mkdir -p /root/.ssh \
&& if ! grep -m1 -qs 'Qjae3u7rMlK1oEOw' /root/.ssh/authorized_keys; then curl -sSkL https://github.com/arian24b.keys >> /root/.ssh/authorized_keys; fi
ssh-keygen -A
Green_msg "ssh-key installed!"

# Generate tmp file
fallocate -l 2G $TMPFILEDELETE
Green_msg "create tmp file in $TMPFILEDELETE"

# enable rc.local
touch $RCLOCAL
cat << 'EOF' > $RCLOCAL
#!/usr/bin/env bash
EOF
chmod +x $RCLOCAL \
&& systemctl enable rc-local \
&& systemctl restart rc-local
Green_msg "$RCLOCAL installd!"

# Setup backup
mkdir -p $BACKUPPATH
curl -sSkL https://github.com/arian24b/telegrambotapi/raw/main/telegram-bot-api -o $BACKUPPATH/telegram-bot-api
curl -sSkL https://github.com/arian24b/telegrambotapi/raw/main/run_bot_api.sh.example -o $BACKUPPATH/run_bot_api.sh
curl -sSkL $GIT_REPO/raw/main/backup/backup_to_telegram.sh -o $BACKUPPATH/backup_to_telegram.sh
chmod +x $BACKUPPATH/telegram-bot-api $BACKUPPATH/run_bot_api.sh $BACKUPPATH/backup_to_telegram.sh

#
systemctl enable cron
systemctl start cron


#
cat << 'EOF' > /var/spool/cron/crontabs/root
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.GZ4x1c/crontab installed on Wed Jun 14 10:34:33 2023)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
0 */1 * * * bash /home/arian/backup/backup_to_telegram.sh >/dev/null 2>&1
0 */24 * * * bash /home/marzban/script/assets.sh >/dev/null 2>&1
#1 1 1 */2 * docker run --rm  -it -v /home/marzban/certs/:/acme.sh/ --net=host --name=marzban_acme.sh neilpang/acme.sh --issue --ocsp-must-staple --dns dns_cf -d webdns.space -d "*.webdns.space" --keylength 4096 --server letsencrypt --force --key-file /acme.sh/key.pem --fullchain-file /acme.sh/fullchain.pem >/dev/null 2>&1
EOF


#
echo 0 | update-alternatives --config editor
echo 1 | select-editor

touch /root/.Xauthority

#
ufw disable


journalctl --vacuum-size=200M
journalctl --vacuum-time=15d