services:
  marzban:
    container_name: marzban
    image: gozargah/marzban:v0.8.4
    restart: always
    env_file: .env
    ports:
      - "2053:2053"
      - "2087:2087"
      - "2083:2083"
      - "2096:2096"
      - "127.0.0.1:8008:8000"
    volumes:
      - ${HPATH}:${VPATH}
