services:
  marzban:
    container_name: marzban
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    ports:
      - "2053:2053"
      - "2082:2082"
      - "2083:2083"
      - "2096:2096"
    volumes:
      - ${HPATH}:${VPATH}
    networks:
      - marzban_network
  tunnel:
    depends_on:
      - marzban
    container_name: marzban_tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    env_file: .env
    restart: always
    networks:
      - marzban_network
networks:
  marzban_network:
    driver: bridge